version: "3"
services:
  myportfolio:
    container_name: myporfolio
    build: .
    restart: always
    env_file:
      - example.env
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
    - example.env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase: