name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Setup Python Virtual Environment
        run: python3 -m venv python3-virtualenv

      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Start Flask Server
        run: |
          python3-virtualenv/bin/python app.py &
          sleep 5  # Wait for the server to start

      - name: Run Tests
        run: ./run_test.sh